In [1]:
import pandas as pd
import glob
import os
os.chdir("CSV")

In [2]:
extension = 'csv'
all_filenames = [i for i in glob.glob('*.{}'.format(extension))]

In [3]:
all_filenames

['202106-citibike-tripdata.csv',
 '202107-citibike-tripdata.csv',
 '202108-citibike-tripdata.csv',
 '202109-citibike-tripdata.csv']

In [4]:
#combine all files in the list
combined_csv = pd.concat([pd.read_csv(f, low_memory=False) for f in all_filenames ])
#export to csv
combined_csv.to_csv( "combined_csv.csv", index=False, encoding='utf-8-sig')

In [5]:
df = pd.read_csv("combined_csv.csv", low_memory=False)
df

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual
0,6339C86D47EC0FAB,docked_bike,2021-06-02 17:18:45,2021-06-02 17:26:17,W 51 St & 6 Ave,6740.10,E 66 St & Madison Ave,6969.08,40.760659,-73.980420,40.768009,-73.968453,member
1,CDE3C147775B4002,docked_bike,2021-06-04 21:01:46,2021-06-04 21:32:09,W 56 St & 10 Ave,6955.01,E 9 St & Avenue C,5616.01,40.768254,-73.988639,40.725213,-73.977688,member
2,D335C3F6B412B846,docked_bike,2021-06-15 16:39:36,2021-06-15 16:55:02,E 56 St & Madison Ave,6732.01,E 16 St & 5 Ave,6022.04,40.761573,-73.972628,40.737262,-73.992390,member
3,8DA6810777C89735,docked_bike,2021-06-08 11:36:40,2021-06-08 11:39:41,E 68 St & 3 Ave,6896.16,1 Ave & E 62 St,6753.08,40.767128,-73.962246,40.761227,-73.960940,member
4,62D9B66A3A1D9FDF,docked_bike,2021-06-18 12:48:43,2021-06-18 13:04:14,E 48 St & 5 Ave,6626.01,W 20 St & 8 Ave,6224.05,40.757245,-73.978059,40.743453,-74.000040,member
...,...,...,...,...,...,...,...,...,...,...,...,...,...
12614748,8A1C8DB4249BF100,classic_bike,2021-09-26 16:00:45,2021-09-26 16:20:51,8 Ave & W 31 St,6450.05,W 67 St & Broadway,7116.04,40.750585,-73.994685,40.774925,-73.982666,casual
12614749,C290EE73DF58AD79,classic_bike,2021-09-07 08:22:06,2021-09-07 08:38:40,S Portland Ave & Hanson Pl,4354.05,S 3 St & Bedford Ave,5235.05,40.685396,-73.974315,40.712605,-73.962644,casual
12614750,E42F8B93C4168658,classic_bike,2021-09-30 20:50:23,2021-09-30 20:59:13,West End Ave & W 60 St,7059.08,Amsterdam Ave & W 66 St,7149.05,40.772370,-73.990050,40.774667,-73.984706,casual
12614751,7221F0C58026A827,classic_bike,2021-09-08 19:06:24,2021-09-08 19:10:57,West End Ave & W 60 St,7059.08,Amsterdam Ave & W 66 St,7149.05,40.772370,-73.990050,40.774667,-73.984706,member
12614752,689F3FAE372C013C,classic_bike,2021-09-27 07:58:57,2021-09-27 08:02:31,West End Ave & W 60 St,7059.08,W 67 St & Broadway,7116.04,40.772370,-73.990050,40.774925,-73.982666,member

In [6]:
# check if any NaN values
df.isnull().values.any()

True

In [7]:
# count total Nan values
df.isnull().sum().sum()

169188

In [8]:
# inspect rows that have NaN values
is_NaN = df.isnull()
row_has_NaN = is_NaN.any(axis=1)
rows_with_NaN = df[row_has_NaN]

print(rows_with_NaN)

                   ride_id rideable_type           started_at  \
23234     09E4544A12073CC0   docked_bike  2021-06-15 07:45:51
23241     129DBED1C3D74391   docked_bike  2021-06-17 16:36:59
23245     5407DDDA74522213  classic_bike  2021-06-28 21:08:47
23252     F74145A9BEA27580  classic_bike  2021-06-28 23:02:31
23256     5AA512DEF0F6869C   docked_bike  2021-06-04 10:51:03
...                    ...           ...                  ...
12586038  B606A471FF796C76  classic_bike  2021-09-05 11:35:28
12586076  415D4A081337C864  classic_bike  2021-09-22 14:51:41
12586077  034CA0469DC447FA  classic_bike  2021-09-18 14:54:26
12586082  5CC0BD81DD8D13A7  classic_bike  2021-09-12 20:43:51
12586168  11760EE36B1E6DD9  classic_bike  2021-09-03 07:58:19

                     ended_at          start_station_name  start_station_id  \
23234     2021-06-15 08:04:16      W 76 St & Columbus Ave           7281.09
23241     2021-06-17 16:49:14       Madison Ave & E 26 St           6131.12
23245     2021-06-28 21:26:24          Carmine St & 6 Ave           5763.03
23252     2021-06-30 00:02:26       Morris Ave & E 184 St           8550.04
23256     2021-06-04 11:01:29      Norfolk St & Broome St           5374.01
...                       ...                         ...               ...
12586038  2021-09-05 16:31:24      West End Ave & W 60 St           7059.08
12586076  2021-09-22 15:06:12  S Portland Ave & Hanson Pl           4354.05
12586077  2021-09-18 15:48:45      West End Ave & W 60 St           7059.08
12586082  2021-09-13 00:10:34             8 Ave & W 31 St           6450.05
12586168  2021-09-03 18:27:23             8 Ave & W 31 St           6450.05

         end_station_name end_station_id  start_lat  start_lng  end_lat  \
23234                 NaN            NaN  40.780183 -73.977285      NaN
23241                 NaN            NaN  40.742684 -73.986713      NaN
23245                 NaN            NaN  40.730386 -74.002150      NaN
23252                 NaN            NaN  40.860080 -73.900790      NaN
23256                 NaN            NaN  40.717227 -73.988020      NaN
...                   ...            ...        ...        ...      ...
12586038              NaN            NaN  40.772370 -73.990050      NaN
12586076              NaN            NaN  40.685396 -73.974315      NaN
12586077              NaN            NaN  40.772370 -73.990050      NaN
12586082              NaN            NaN  40.750585 -73.994685    40.74
12586168              NaN            NaN  40.750585 -73.994685      NaN

          end_lng member_casual
23234         NaN        member
23241         NaN        member
23245         NaN        member
23252         NaN        casual
23256         NaN        member
...           ...           ...
12586038      NaN        member
12586076      NaN        member
12586077      NaN        member
12586082   -73.97        member
12586168      NaN        member

[53229 rows x 13 columns]

It appears that most missing values are for end location, end station and end time - journeys that seemingly have not ended. This could be due to:
* Out of battery
* No GPS signal
* Damaged hardware
* Software crash/error
* Bike stolen/not returned
* Accident

In [9]:
#drop null values
cleaned_df = df.dropna()

In [10]:
cleaned_df

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual
0,6339C86D47EC0FAB,docked_bike,2021-06-02 17:18:45,2021-06-02 17:26:17,W 51 St & 6 Ave,6740.10,E 66 St & Madison Ave,6969.08,40.760659,-73.980420,40.768009,-73.968453,member
1,CDE3C147775B4002,docked_bike,2021-06-04 21:01:46,2021-06-04 21:32:09,W 56 St & 10 Ave,6955.01,E 9 St & Avenue C,5616.01,40.768254,-73.988639,40.725213,-73.977688,member
2,D335C3F6B412B846,docked_bike,2021-06-15 16:39:36,2021-06-15 16:55:02,E 56 St & Madison Ave,6732.01,E 16 St & 5 Ave,6022.04,40.761573,-73.972628,40.737262,-73.992390,member
3,8DA6810777C89735,docked_bike,2021-06-08 11:36:40,2021-06-08 11:39:41,E 68 St & 3 Ave,6896.16,1 Ave & E 62 St,6753.08,40.767128,-73.962246,40.761227,-73.960940,member
4,62D9B66A3A1D9FDF,docked_bike,2021-06-18 12:48:43,2021-06-18 13:04:14,E 48 St & 5 Ave,6626.01,W 20 St & 8 Ave,6224.05,40.757245,-73.978059,40.743453,-74.000040,member
...,...,...,...,...,...,...,...,...,...,...,...,...,...
12614748,8A1C8DB4249BF100,classic_bike,2021-09-26 16:00:45,2021-09-26 16:20:51,8 Ave & W 31 St,6450.05,W 67 St & Broadway,7116.04,40.750585,-73.994685,40.774925,-73.982666,casual
12614749,C290EE73DF58AD79,classic_bike,2021-09-07 08:22:06,2021-09-07 08:38:40,S Portland Ave & Hanson Pl,4354.05,S 3 St & Bedford Ave,5235.05,40.685396,-73.974315,40.712605,-73.962644,casual
12614750,E42F8B93C4168658,classic_bike,2021-09-30 20:50:23,2021-09-30 20:59:13,West End Ave & W 60 St,7059.08,Amsterdam Ave & W 66 St,7149.05,40.772370,-73.990050,40.774667,-73.984706,casual
12614751,7221F0C58026A827,classic_bike,2021-09-08 19:06:24,2021-09-08 19:10:57,West End Ave & W 60 St,7059.08,Amsterdam Ave & W 66 St,7149.05,40.772370,-73.990050,40.774667,-73.984706,member
12614752,689F3FAE372C013C,classic_bike,2021-09-27 07:58:57,2021-09-27 08:02:31,West End Ave & W 60 St,7059.08,W 67 St & Broadway,7116.04,40.772370,-73.990050,40.774925,-73.982666,member

As you can see above we have now dropped exactly 53,229 rows which were the rows containing NaN values

In [11]:
difference = (len(cleaned_df)/len(df)) * 100
print(difference)

99.5780416786599

As you can see we still have 99.57% of our original data! I'm happy with only dropping just over 0.4% of the data.

In [12]:
## export the data
cleaned_df.to_csv("cleaned_citibike_data.csv")